name: CI Pipeline

# trigger pipeline on every push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    #  checkout repository code to the runner workspace
    - name: Checkout repository
      uses: actions/checkout@v4

    #  build the development stage. 
    - name: build development image and run tests
      run: |
        cd python-app
        docker build --target development --build-arg NAME="aziz" -t python-app:dev .

    #  build final production image.
    - name: build final production image
      run: |
        cd python-app
        docker build --target production --build-arg NAME="aziz" -t python-app:latest .
